apiVersion: v1
kind: Service
metadata:
  name: linkdingc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.178.222
spec:
  ports:
    - port: 3003
  selector:
    app: linkding
  type: ClusterIP
