apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: traefik-config
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/component: traefik
configurations:
  - kustomizeconfig.yaml
