apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: traefik
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
    valuesKey: values.yaml