apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: cert-manager-config
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/component: cert-manager
configurations:
  - kustomizeconfig.yaml