apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: '1.12.*'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 5m
  install:
    createNamespace: true
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-config
    valuesKey: values.yaml