apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - svc.yaml
  - deployment.yaml
  - pvc.yaml
  - configmap.yaml
  - _init/job.yaml
  - _init/rbac.yaml
configMapGenerator:
- name: homelab-init
  files:
  - _init/create-secret-via-kubectl.sh
  options:
    disableNameSuffixHash: true