apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi