apiVersion: v1
kind: Service
metadata:
  name: linkdingc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.178.181
spec:
  type: LoadBalancer
  selector:
    app: linkding
  ports:
    - port: 3003
      targetPort: 3003